<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Upload extends Model
{
    protected $fillable = ['fillable'];


    public function users(){
        return $this->belongsTo(User::class);

    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function (Upload $upload){

            unlink(realpath('../public/app/'));
        });
    }


}
