<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Upload extends Model
{

    //The fillable property defines which attributes may be assignable.
    protected $fillable = ['fillable'];


    //The relationships between upload and user and upload and file are defined here.

    public function user()
    {
        return $this->belongsTo(User::class);
    }


    public function upload()
    {
        return $this->hasOne(Upload::class);
    }

    //This function is used to delete an uploaded file.

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function (File $file){

            unlink(realpath('../storage/app/'.$file->upload->filename));
            $file->upload->delete();
        });
    }

}
